package CROSS.Utils;

/**
 * 
 * Class to generate unique numbers.
 * Used to generate unique IDs for orders.
 * 
 * @version 1.0
 * @author Giulio Nisi
 * 
 */
public class UniqueNumber {
    
    // Class level variables to store the last time and the last number generated.
    private static Long lastTime = Long.valueOf(0);
    private static Long lastNumber = null;
    
    private final Long number;

    /**
     * 
     * Constructor to generate a unique number.
     * 
     * The number is generated by concatenating the current time in milliseconds and a number that increments if the time is the same.
     * Why? 
     * 1. The time in milliseconds is used to avoid getting the same number in different instances / runs of the program.
     * 2. The number is used to avoid getting the same number by 2 threads in the same millisecond.
     * 
     * It is synchronized ON CLASS to avoid conflicts between threads.
     * 
     */
    public UniqueNumber() {

        synchronized (UniqueNumber.class) {

            long currentTime = System.currentTimeMillis();

            if (currentTime == lastTime.longValue()) {
                lastNumber++;
            } else {
                lastTime = Long.valueOf(currentTime);
                lastNumber = Long.valueOf(0);
            }
            
            this.number = lastTime + lastNumber;

        }

    }

    // GETTERS
    /**
     * 
     * Get the unique number.
     * 
     * @return The unique number as Long.
     * 
     */
    public Long getNumber() {

        return Long.valueOf(this.number);

    }

}
