package cross.utils;

/**
 *
 * Class to generate unique numbers.
 *
 * Used to generate unique IDs for orders.
 *
 * @version 1.0
 * @author Giulio Nisi
 * 
 * @see cross.orders.Order
 *
 */
public class UniqueNumber {

    // To save the last timestamp in nanoseconds.
    private static Long lastTimeMillis = System.nanoTime();
    // A counter to be used in case of same timestamp requests.
    private static Long counter = 0L;

    private final Long number;

    /**
     *
     * Constructor to generate a unique number.
     *
     * The number is generated by getting the current time in nanoseconds and adding a counter to it.
     * Why?
     * The time in nanoseconds is used to avoid getting the same number in different instances / runs of the program.
     * The counter, instead, is used to avoid getting the same number in requests that are made in the same nanosecond.
     *
     * It is synchronized ON CLASS to avoid conflicts between threads.
     *
     */
    public UniqueNumber() {

        synchronized (UniqueNumber.class) {

            // Use the current time in nanoseconds.
            // DO NOT USE System.currentTimeMillis() because it's not precise enough!
            Long currentTime = System.nanoTime();

            // If the current time is less than the last time, set it to the last time.
            // To avoid clock unprecision.
            if (currentTime < lastTimeMillis) {
                currentTime = lastTimeMillis;
            }

            if (currentTime.compareTo(lastTimeMillis) == 0) {
                counter++;
            }else {
                lastTimeMillis = currentTime;
                counter = 0L;
            }

            this.number = currentTime  + counter;

        }

    }

    // GETTERS
    /**
     *
     * Get the unique number.
     *
     * @return The unique number as Long.
     *
     */
    public Long getNumber() {

        return this.number;

    }

    @Override
    public String toString() {

        return this.number.toString();

    }

}
